[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chiptune-tools"
version = "0.5"
authors = [
  {name = "std282"}
]
requires-python = ">=3.10"
license = "MIT"
